import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within LanguageProvider');
    }
    return context;
};

const translations = {
    en: {
        // Navigation
        home: 'Home',
        history: 'History',
        logout: 'Logout',
        // Main page
        futureSimulator: 'FutureVision',
        hi: 'Hi',
        discoverYourFuture: 'Discover your future',
        yourSkillOrProject: 'Your skill or project',
        skillPlaceholder: 'Example: Python development, AI/ML, web design...',
        currentLevel: 'Current Level',
        beginner: 'Beginner',
        intermediate: 'Intermediate',
        advanced: 'Advanced',
        test: 'Test',
        timeHorizon: 'Time Horizon',
        year: 'year',
        years: 'years',
        showMyFuture: 'Show my future',
        lookingIntoTheFuture: 'Looking into the future...',
        pleaseEnterSkill: 'Please enter a skill or project',
        rudeWordDetected: 'Rude word detected!!',
        // Predictions
        yourDirection: 'Your Direction',
        keyMilestones: 'Key Milestones',
        progress: 'Progress',
        opportunities: 'Opportunities',
        risks: 'Risks',
        nextSteps: 'Next Steps',
        completed: 'Completed',
        addNotes: 'Add notes',
        save: 'Save',
        cancel: 'Cancel',
        notesPlaceholder: 'Add notes about this milestone...',
        // History
        selectAll: 'Select All',
        compare: 'Compare',
        delete: 'Delete',
        noPredictions: 'No predictions yet',
        predictionHistory: 'Prediction History',
        predictionsSelected: 'predictions selected',
        milestones: 'milestones',
        view: 'View',
        startByCreating: 'Start by creating your first prediction!',
        // Export
        exportAsPDF: 'Export as PDF',
        share: 'Share',
        // Learning Resources
        learningResources: 'Learning Resources',
        courses: 'Courses',
        books: 'Books',
        documentation: 'Documentation',
        by: 'by',
        featuredPlatform: 'Featured Platform',
        discoverMoreResources: 'Discover more learning resources',
        // Landing
        findOutWhere: 'Find out where your skill will lead you',
        logIn: 'Log In',
        createAccount: 'Create Account',
        continueWithoutRegistration: 'Continue without registration',
        goToAccount: 'Go to Account',
        continueToApp: 'Continue to App',
        // Login/Register
        email: 'Email',
        password: 'Password',
        name: 'Name',
        yourName: 'Your name',
        emailPlaceholder: 'your@email.com',
        passwordPlaceholder: '••••••••',
        registration: 'Registration',
        dontHaveAccount: "Don't have an account? Sign Up",
        alreadyHaveAccount: 'Already have an account? Login',
        // Test Modal
        question: 'Question',
        of: 'of',
        testQuestion1: 'How long have you been working on this skill?',
        testQuestion2: 'Can you create projects independently?',
        testQuestion3: 'How often do you practice?',
        testQuestion4: 'Do you understand the basic concepts?',
        testOption1_1: 'Only started',
        testOption1_2: '1-6 months',
        testOption1_3: '6-12 months',
        testOption1_4: 'More than a year',
        testOption2_1: 'No, need help',
        testOption2_2: 'Simple - yes',
        testOption2_3: 'Medium complexity - yes',
        testOption2_4: 'Complex - yes',
        testOption3_1: 'Rarely',
        testOption3_2: '1-2 times a week',
        testOption3_3: '3-5 times a week',
        testOption3_4: 'Every day',
        testOption4_1: 'Not at all',
        testOption4_2: 'Surface level',
        testOption4_3: 'Good',
        testOption4_4: 'Excellent, can explain',
        // Comparison
        loadingComparison: 'Loading comparison...',
        needAtLeast2: 'Need at least 2 predictions to compare',
        comparePredictions: 'Compare Predictions',
        milestonesComparison: 'Milestones Comparison',
        period: 'Period',
        milestone: 'Milestone',
        // Export/Share
        exportShare: 'Export & Share',
        export: 'Export',
        exportPDF: 'Export PDF',
        exportMarkdown: 'Export Markdown',
        shareLink: 'Share Link',
        copy: 'Copy',
        copied: 'Copied!',
        shareOnSocialMedia: 'Share on Social Media',
        twitter: 'Twitter',
        linkedin: 'LinkedIn',
        facebook: 'Facebook',
        // Account
        account: 'Account',
        totalPredictions: 'Total Predictions',
        completedPredictions: 'Completed',
        totalMilestones: 'Total Milestones',
        memberSince: 'Member Since',
        viewFullHistory: 'View Full History',
        back: 'Back',
        pleaseEnterEmailAndPassword: 'Please enter email and password',
        pleaseFillAllFields: 'Please fill all fields',
        loginFailed: 'Login failed',
        registrationFailed: 'Registration failed',
        loggingIn: 'Logging in...',
        creatingAccount: 'Creating account...',
        // Common
        loading: 'Loading...',
        error: 'Error',
        generated: 'Generated',
    },
    ru: {
        // Navigation
        home: 'Главная',
        history: 'История',
        logout: 'Выйти',
        // Main page
        futureSimulator: 'FutureVision',
        hi: 'Привет',
        discoverYourFuture: 'Откройте свое будущее',
        yourSkillOrProject: 'Ваш навык или проект',
        skillPlaceholder: 'Пример: Разработка на Python, AI/ML, веб-дизайн...',
        currentLevel: 'Текущий уровень',
        beginner: 'Начинающий',
        intermediate: 'Средний',
        advanced: 'Продвинутый',
        test: 'Тест',
        timeHorizon: 'Временной горизонт',
        year: 'год',
        years: 'лет',
        showMyFuture: 'Показать мое будущее',
        lookingIntoTheFuture: 'Заглядываю в будущее...',
        pleaseEnterSkill: 'Пожалуйста, введите навык или проект',
        rudeWordDetected: 'Обнаружено грубое слово!!',
        // Predictions
        yourDirection: 'Ваше направление',
        keyMilestones: 'Ключевые вехи',
        progress: 'Прогресс',
        opportunities: 'Возможности',
        risks: 'Риски',
        nextSteps: 'Следующие шаги',
        completed: 'Завершено',
        addNotes: 'Добавить заметки',
        save: 'Сохранить',
        cancel: 'Отмена',
        notesPlaceholder: 'Добавьте заметки об этой вехе...',
        // History
        selectAll: 'Выбрать все',
        compare: 'Сравнить',
        delete: 'Удалить',
        noPredictions: 'Пока нет прогнозов',
        predictionHistory: 'История прогнозов',
        predictionsSelected: 'прогнозов выбрано',
        milestones: 'вех',
        view: 'Просмотр',
        startByCreating: 'Начните с создания вашего первого прогноза!',
        // Export
        exportAsPDF: 'Экспорт в PDF',
        share: 'Поделиться',
        // Learning Resources
        learningResources: 'Обучающие ресурсы',
        courses: 'Курсы',
        books: 'Книги',
        documentation: 'Документация',
        by: 'от',
        featuredPlatform: 'Рекомендуемая платформа',
        discoverMoreResources: 'Откройте для себя больше обучающих ресурсов',
        // Landing
        findOutWhere: 'Узнайте, куда приведет вас ваш навык',
        logIn: 'Войти',
        createAccount: 'Создать аккаунт',
        continueWithoutRegistration: 'Продолжить без регистрации',
        goToAccount: 'Перейти в аккаунт',
        continueToApp: 'Продолжить в приложение',
        // Login/Register
        email: 'Email',
        password: 'Пароль',
        name: 'Имя',
        yourName: 'Ваше имя',
        emailPlaceholder: 'ваш@email.com',
        passwordPlaceholder: '••••••••',
        registration: 'Регистрация',
        dontHaveAccount: 'Нет аккаунта? Зарегистрироваться',
        alreadyHaveAccount: 'Уже есть аккаунт? Войти',
        // Test Modal
        question: 'Вопрос',
        of: 'из',
        testQuestion1: 'Как долго вы работаете над этим навыком?',
        testQuestion2: 'Можете ли вы создавать проекты самостоятельно?',
        testQuestion3: 'Как часто вы практикуетесь?',
        testQuestion4: 'Понимаете ли вы основные концепции?',
        testOption1_1: 'Только начал',
        testOption1_2: '1-6 месяцев',
        testOption1_3: '6-12 месяцев',
        testOption1_4: 'Более года',
        testOption2_1: 'Нет, нужна помощь',
        testOption2_2: 'Простые - да',
        testOption2_3: 'Средней сложности - да',
        testOption2_4: 'Сложные - да',
        testOption3_1: 'Редко',
        testOption3_2: '1-2 раза в неделю',
        testOption3_3: '3-5 раз в неделю',
        testOption3_4: 'Каждый день',
        testOption4_1: 'Совсем нет',
        testOption4_2: 'Поверхностно',
        testOption4_3: 'Хорошо',
        testOption4_4: 'Отлично, могу объяснить',
        // Comparison
        loadingComparison: 'Загрузка сравнения...',
        needAtLeast2: 'Нужно минимум 2 прогноза для сравнения',
        comparePredictions: 'Сравнить прогнозы',
        milestonesComparison: 'Сравнение вех',
        period: 'Период',
        milestone: 'Веха',
        // Export/Share
        exportShare: 'Экспорт и Поделиться',
        export: 'Экспорт',
        exportPDF: 'Экспорт PDF',
        exportMarkdown: 'Экспорт Markdown',
        shareLink: 'Поделиться ссылкой',
        copy: 'Копировать',
        copied: 'Скопировано!',
        shareOnSocialMedia: 'Поделиться в соцсетях',
        twitter: 'Twitter',
        linkedin: 'LinkedIn',
        facebook: 'Facebook',
        // Account
        account: 'Аккаунт',
        totalPredictions: 'Всего прогнозов',
        completedPredictions: 'Завершено',
        totalMilestones: 'Всего вех',
        memberSince: 'Участник с',
        viewFullHistory: 'Просмотреть всю историю',
        back: 'Назад',
        pleaseEnterEmailAndPassword: 'Пожалуйста, введите email и пароль',
        pleaseFillAllFields: 'Пожалуйста, заполните все поля',
        loginFailed: 'Ошибка входа',
        registrationFailed: 'Ошибка регистрации',
        loggingIn: 'Вход...',
        creatingAccount: 'Создание аккаунта...',
        // Common
        loading: 'Загрузка...',
        error: 'Ошибка',
        generated: 'Создано',
    },
    hy: {
        // Navigation
        home: 'Գլխավոր',
        history: 'Պատմություն',
        logout: 'Ելք',
        // Main page
        futureSimulator: 'FutureVision',
        hi: 'Ողջույն',
        discoverYourFuture: 'Բացահայտեք ձեր ապագան',
        yourSkillOrProject: 'Ձեր հմտությունը կամ նախագիծը',
        skillPlaceholder: 'Օրինակ: Python ծրագրավորում, AI/ML, վեբ դիզայն...',
        currentLevel: 'Ներկա մակարդակ',
        beginner: 'Սկսնակ',
        intermediate: 'Միջին',
        advanced: 'Ընդլայնված',
        test: 'Փորձարկում',
        timeHorizon: 'Ժամանակային հորիզոն',
        year: 'տարի',
        years: 'տարի',
        showMyFuture: 'Ցույց տալ իմ ապագան',
        lookingIntoTheFuture: 'Նայում եմ ապագային...',
        pleaseEnterSkill: 'Խնդրում ենք մուտքագրել հմտություն կամ նախագիծ',
        rudeWordDetected: 'Բռնություն հայտնաբերված!!',
        // Predictions
        yourDirection: 'Ձեր ուղղությունը',
        keyMilestones: 'Հիմնական հատվածներ',
        progress: 'Առաջընթաց',
        opportunities: 'Հնարավորություններ',
        risks: 'Ռիսկեր',
        nextSteps: 'Հաջորդ քայլեր',
        completed: 'Ավարտված',
        addNotes: 'Ավելացնել նշումներ',
        save: 'Պահպանել',
        cancel: 'Չեղարկել',
        notesPlaceholder: 'Ավելացրեք նշումներ այս հատվածի մասին...',
        // History
        selectAll: 'Ընտրել բոլորը',
        compare: 'Համեմատել',
        delete: 'Ջնջել',
        noPredictions: 'Դեռևս կանխատեսումներ չկան',
        predictionHistory: 'Կանխատեսումների Պատմություն',
        predictionsSelected: 'կանխատեսումներ ընտրված',
        milestones: 'հատվածներ',
        view: 'Դիտել',
        startByCreating: 'Սկսեք ձեր առաջին կանխատեսումը ստեղծելով!',
        // Export
        exportAsPDF: 'Արտահանել PDF',
        share: 'Կիսվել',
        // Learning Resources
        learningResources: 'Ուսումնական ռեսուրսներ',
        courses: 'Դասընթացներ',
        books: 'Գրքեր',
        documentation: 'Փաստաթղթավորում',
        by: 'հեղինակ',
        featuredPlatform: 'Առաջարկվող հարթակ',
        discoverMoreResources: 'Բացահայտեք ավելի շատ ուսումնական ռեսուրսներ',
        // Landing
        findOutWhere: 'Պարզեք, թե որտեղ կտանի ձեր հմտությունը',
        logIn: 'Մուտք',
        createAccount: 'Ստեղծել հաշիվ',
        continueWithoutRegistration: 'Շարունակել առանց գրանցման',
        goToAccount: 'Գնալ հաշիվ',
        continueToApp: 'Շարունակել հավելվածում',
        // Login/Register
        email: 'Էլ. փոստ',
        password: 'Գաղտնաբառ',
        name: 'Անուն',
        yourName: 'Ձեր անունը',
        emailPlaceholder: 'ձեր@email.com',
        passwordPlaceholder: '••••••••',
        registration: 'Գրանցում',
        dontHaveAccount: 'Չունե՞ք հաշիվ: Գրանցվել',
        alreadyHaveAccount: 'Արդեն ունե՞ք հաշիվ: Մուտք',
        // Test Modal
        question: 'Հարց',
        of: 'ից',
        testQuestion1: 'Որքա՞ն ժամանակ եք աշխատել այս հմտության վրա',
        testQuestion2: 'Կարո՞ղ եք ինքնուրույն նախագծեր ստեղծել',
        testQuestion3: 'Որքա՞ն հաճախ եք պրակտիկա անում',
        testQuestion4: 'Հասկանու՞մ եք հիմնական հասկացությունները',
        testOption1_1: 'Նոր եմ սկսել',
        testOption1_2: '1-6 ամիս',
        testOption1_3: '6-12 ամիս',
        testOption1_4: 'Մեկ տարուց ավելի',
        testOption2_1: 'Ոչ, օգնություն է պետք',
        testOption2_2: 'Պարզ - այո',
        testOption2_3: 'Միջին բարդություն - այո',
        testOption2_4: 'Բարդ - այո',
        testOption3_1: 'Հազվադեպ',
        testOption3_2: 'Շաբաթը 1-2 անգամ',
        testOption3_3: 'Շաբաթը 3-5 անգամ',
        testOption3_4: 'Ամեն օր',
        testOption4_1: 'Ընդհանրապես ոչ',
        testOption4_2: 'Մակերեսային',
        testOption4_3: 'Լավ',
        testOption4_4: 'Գերազանց, կարող եմ բացատրել',
        // Comparison
        loadingComparison: 'Համեմատությունը բեռնվում է...',
        needAtLeast2: 'Պետք է առնվազն 2 կանխատեսում համեմատելու համար',
        comparePredictions: 'Համեմատել կանխատեսումները',
        milestonesComparison: 'Հատվածների համեմատություն',
        period: 'ժամանակաշրջան',
        milestone: 'Հատված',
        // Export/Share
        exportShare: 'Արտահանել և Կիսվել',
        export: 'Արտահանել',
        exportPDF: 'Արտահանել PDF',
        exportMarkdown: 'Արտահանել Markdown',
        shareLink: 'Կիսվել հղումով',
        copy: 'Պատճենել',
        copied: 'Պատճենված է!',
        shareOnSocialMedia: 'Կիսվել սոցիալական ցանցերում',
        twitter: 'Twitter',
        linkedin: 'LinkedIn',
        facebook: 'Facebook',
        // Account
        account: 'Հաշիվ',
        totalPredictions: 'Ընդհանուր կանխատեսումներ',
        completedPredictions: 'Ավարտված',
        totalMilestones: 'Ընդհանուր հատվածներ',
        memberSince: 'Անդամ է սկսած',
        viewFullHistory: 'Դիտել ամբողջ պատմությունը',
        back: 'Վերադառնալ',
        pleaseEnterEmailAndPassword: 'Խնդրում ենք մուտքագրել էլ. փոստ և գաղտնաբառ',
        pleaseFillAllFields: 'Խնդրում ենք լրացնել բոլոր դաշտերը',
        loginFailed: 'Մուտքը ձախողվեց',
        registrationFailed: 'Գրանցումը ձախողվեց',
        loggingIn: 'Մուտք...',
        creatingAccount: 'Հաշիվ ստեղծվում է...',
        // Common
        loading: 'Բեռնվում է...',
        error: 'Սխալ',
        generated: 'Ստեղծված',
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(() => {
        const saved = localStorage.getItem('futureSimulatorLanguage');
        return saved || 'en';
    });

    useEffect(() => {
        localStorage.setItem('futureSimulatorLanguage', language);
    }, [language]);

    const t = (key) => {
        return translations[language]?.[key] || translations.en[key] || key;
    };

    const changeLanguage = (lang) => {
        setLanguage(lang);
    };

    return (
        <LanguageContext.Provider value={{ language, changeLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

