import React, { useState } from 'react';
import { Download, Image, Copy, Check, Share2 } from 'lucide-react';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

export default function ExportButtons({ predictions, skill, elementId = 'prediction-content' }) {
    const [copied, setCopied] = useState(false);
    const [exporting, setExporting] = useState(false);

    const exportAsPDF = async () => {
        setExporting(true);
        try {
            const element = document.getElementById(elementId);
            if (!element) {
                alert('Content not found');
                return;
            }

            const canvas = await html2canvas(element, {
                scale: 2,
                backgroundColor: '#1e1b4b',
                logging: false
            });

            const imgData = canvas.toDataURL('image/png');
            const pdf = new jsPDF({
                orientation: 'portrait',
                unit: 'mm',
                format: 'a4'
            });

            const imgWidth = 210;
            const imgHeight = (canvas.height * imgWidth) / canvas.width;

            pdf.addImage(imgData, 'PNG', 0, 0, imgWidth, imgHeight);
            pdf.save(`futurevision-${skill || 'prediction'}.pdf`);
        } catch (error) {
            console.error('PDF export error:', error);
            alert('Failed to export PDF. Please try again.');
        } finally {
            setExporting(false);
        }
    };

    const exportAsImage = async () => {
        setExporting(true);
        try {
            const element = document.getElementById(elementId);
            if (!element) {
                alert('Content not found');
                return;
            }

            const canvas = await html2canvas(element, {
                scale: 2,
                backgroundColor: '#1e1b4b',
                logging: false
            });

            canvas.toBlob((blob) => {
                const url = URL.createObjectURL(blob);
                const link = document.createElement('a');
                link.href = url;
                link.download = `futurevision-${skill || 'prediction'}.png`;
                link.click();
                URL.revokeObjectURL(url);
            });
        } catch (error) {
            console.error('Image export error:', error);
            alert('Failed to export image. Please try again.');
        } finally {
            setExporting(false);
        }
    };

    const copyToClipboard = async () => {
        try {
            const text = `
🔮 FutureVision Prediction - ${skill}

📈 TRAJECTORY:
${predictions.trajectory}

⏰ KEY MILESTONES:
${predictions.milestones.map((m, i) => `${i + 1}. ${m.period}: ${m.achievement}\n   Skills: ${m.skills.join(', ')}`).join('\n')}

🚀 OPPORTUNITIES:
${predictions.opportunities.map((o, i) => `${i + 1}. ${o}`).join('\n')}

⚠️ RISKS:
${predictions.risks.map((r, i) => `${i + 1}. ${r}`).join('\n')}

📋 NEXT STEPS:
${predictions.nextSteps.map((s, i) => `${i + 1}. ${s}`).join('\n')}

Generated by FutureVision
            `.trim();

            await navigator.clipboard.writeText(text);
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        } catch (error) {
            console.error('Copy error:', error);
            alert('Failed to copy to clipboard');
        }
    };

    return (
        <div className="flex flex-wrap gap-3 mb-6">
            <button
                onClick={exportAsPDF}
                disabled={exporting}
                className="flex items-center gap-2 px-4 py-2 bg-red-500/20 hover:bg-red-500/30 border border-red-400/50 text-red-100 rounded-lg transition-all disabled:opacity-50"
            >
                <Download className="w-4 h-4" />
                {exporting ? 'Exporting...' : 'Export PDF'}
            </button>

            <button
                onClick={exportAsImage}
                disabled={exporting}
                className="flex items-center gap-2 px-4 py-2 bg-blue-500/20 hover:bg-blue-500/30 border border-blue-400/50 text-blue-100 rounded-lg transition-all disabled:opacity-50"
            >
                <Image className="w-4 h-4" />
                {exporting ? 'Exporting...' : 'Export Image'}
            </button>

            <button
                onClick={copyToClipboard}
                className="flex items-center gap-2 px-4 py-2 bg-green-500/20 hover:bg-green-500/30 border border-green-400/50 text-green-100 rounded-lg transition-all"
            >
                {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                {copied ? 'Copied!' : 'Copy Text'}
            </button>
        </div>
    );
}
